# Generated by Django 3.2.17 on 2023-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoscowContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_1', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 1')),
                ('bot_2', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 2')),
                ('bot_3', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 3')),
                ('bot_4', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 4')),
                ('bot_5', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 5')),
                ('ac_bot', models.URLField(blank=True, null=True, verbose_name='Аккаунт-Бот Москва/Питер')),
                ('bot', models.URLField(blank=True, null=True, verbose_name='Бот Москва/Питер Айклад')),
                ('hand_sell', models.URLField(blank=True, null=True, verbose_name='Ручные продажи')),
                ('tech_sup', models.URLField(blank=True, null=True, verbose_name='Тех.Поддержка')),
                ('employ_qs', models.URLField(blank=True, null=True, verbose_name='По вопросам устройства')),
            ],
            options={
                'verbose_name': 'Контакты Москва',
                'verbose_name_plural': 'Контакты Москва',
            },
        ),
        migrations.CreateModel(
            name='PeterContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_1', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 1')),
                ('bot_2', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 2')),
                ('bot_3', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 3')),
                ('bot_4', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 4')),
                ('bot_5', models.URLField(blank=True, null=True, verbose_name='Бот Распределитель 5')),
                ('ac_bot', models.URLField(blank=True, null=True, verbose_name='Аккаунт-Бот Москва/Питер')),
                ('bot', models.URLField(blank=True, null=True, verbose_name='Бот Москва/Питер Айклад')),
                ('hand_sell', models.URLField(blank=True, null=True, verbose_name='Ручные продажи')),
                ('tech_sup', models.URLField(blank=True, null=True, verbose_name='Тех.Поддержка')),
                ('employ_qs', models.URLField(blank=True, null=True, verbose_name='По вопросам устройства')),
            ],
            options={
                'verbose_name': 'Контакты Питер',
                'verbose_name_plural': 'Контакты Питер',
            },
        ),
        migrations.CreateModel(
            name='RestOfContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_site', models.URLField(blank=True, null=True, verbose_name='Наш сайт')),
                ('contacts_site', models.URLField(blank=True, null=True, verbose_name='Сайт с контактами')),
                ('site_chips', models.URLField(blank=True, null=True, verbose_name='Сайт чипсы')),
            ],
            options={
                'verbose_name': 'Оставшиеся ссылки',
                'verbose_name_plural': 'Оставшиеся ссылки',
            },
        ),
        migrations.CreateModel(
            name='VoronezhContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_1', models.URLField(blank=True, null=True, verbose_name='Бот 1')),
                ('bot', models.URLField(blank=True, null=True, verbose_name='Бот Воронеж Айклад')),
                ('hand_sell', models.URLField(blank=True, null=True, verbose_name='Ручные продажи')),
                ('tech_sup', models.URLField(blank=True, null=True, verbose_name='Тех.Поддержка')),
                ('employ_qs', models.URLField(blank=True, null=True, verbose_name='По вопросам устройства')),
            ],
            options={
                'verbose_name': 'Контакты Воронеж',
                'verbose_name_plural': 'Контакты Воронеж',
            },
        ),
    ]
