# Generated by Django 3.2.17 on 2023-02-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_alter_testitemmodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Локация')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.testitemmodel', verbose_name='Товар')),
            ],
        ),
    ]
