# Generated by Django 3.2.17 on 2023-02-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_testitemmodel_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testitemmodel',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
