# Generated by Django 3.2.17 on 2023-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moscow', models.CharField(max_length=100, verbose_name='Москва')),
                ('peter', models.CharField(max_length=100, verbose_name='Питер')),
                ('voronezh', models.CharField(max_length=100, verbose_name='Воронеж')),
                ('bot_msk', models.CharField(max_length=100, verbose_name='Бот Мск')),
                ('operator_msk', models.CharField(max_length=100, verbose_name='Оператор Мск')),
                ('sup_msk', models.CharField(max_length=100, verbose_name='Тех Поддержка Мск')),
                ('visitka_msk', models.CharField(max_length=100, verbose_name='Визитка Мск')),
                ('bot_peter', models.CharField(max_length=100, verbose_name='Бот Спб')),
                ('operator_peter', models.CharField(max_length=100, verbose_name='Оператор Спб')),
                ('sup_peter', models.CharField(max_length=100, verbose_name='Тех Поддержка Спб')),
                ('visitka_peter', models.CharField(max_length=100, verbose_name='Визитка Спб')),
                ('bot_bph', models.CharField(max_length=100, verbose_name='Бот ВРН')),
                ('operator_bph', models.CharField(max_length=100, verbose_name='Оператор ВРН')),
                ('sup_bph', models.CharField(max_length=100, verbose_name='Тех Поддержка ВРН')),
            ],
            options={
                'verbose_name': 'Ссылки головы',
                'verbose_name_plural': 'Ссылки головы',
            },
        ),
    ]
